// This file is auto-generated from the DTOs in MemoryPuzzleApi.
// Do not edit this file directly, changes will be overwritten.
class FileGroupDto {
  final String groupId;
  final String groupName;
  final int imageCount;

  FileGroupDto({
    required this.groupId,
    required this.groupName,
    required this.imageCount,
  });
}

class LoginDto {
  final String username;
  final String password;

  LoginDto({
    required this.username,
    required this.password,
  });
}

class PuzzleAdminDto {
  final int id;
  final String name;
  final String creator;
  final DateTime creationTime;
  final int imageCount;
  final bool isPublic;

  PuzzleAdminDto({
    required this.id,
    required this.name,
    required this.creator,
    required this.creationTime,
    required this.imageCount,
    required this.isPublic,
  });
}

class PuzzleDto {
  final int id;
  final String name;
  final DateTime creationTime;
  final String author;
  final String authorRole;
  final bool isPublic;
  final List<PuzzleImageDto> images;

  PuzzleDto({
    required this.id,
    required this.name,
    required this.creationTime,
    required this.author,
    required this.authorRole,
    required this.isPublic,
    required this.images,
  });
}

class PuzzleImageDto {
  final String imageUid;

  PuzzleImageDto({
    required this.imageUid,
  });
}

class UserAdminDto {
  final String username;
  final List<String> roles;
  final DateTime? lastLogin;
  final int puzzleCount;

  UserAdminDto({
    required this.username,
    required this.roles,
    this.lastLogin,
    required this.puzzleCount,
  });
}

