// This file is auto-generated from the API routes in MemoryPuzzleApi.
// Do not edit this file directly, changes will be overwritten.
import '../utils/constants.dart';
class ApiEndpoints {
  static const String apiBaseUrl = AppConstants.apiBaseUrl;
  static final String utilsCreateAdmin = '${AppConstants.apiBaseUrl}/api/v1/utils/admin';
  static final String utilsCreateUsers = '${AppConstants.apiBaseUrl}/api/v1/utils/users';
  static final String utilsDeleteUsers = '${AppConstants.apiBaseUrl}/api/v1/utils/users';
  static final String utilsDartExporterRoutes = '${AppConstants.apiBaseUrl}/api/v1/utils/exportroutes';
  static final String utilsDartExporterDtos = '${AppConstants.apiBaseUrl}/api/v1/utils/exportdtos';
  static final String adminInfo = '${AppConstants.apiBaseUrl}/api/v1/admin/info';
  static final String adminAllUsers = '${AppConstants.apiBaseUrl}/api/v1/admin/users';
  static final String adminAllPuzzles = '${AppConstants.apiBaseUrl}/api/v1/admin/puzzles';
  static final String adminUpdatePuzzle = '${AppConstants.apiBaseUrl}/api/v1/admin/updatepuzzle';
  static final String puzzlesGetAll = '${AppConstants.apiBaseUrl}/api/v1/puzzles';
  static final String puzzlesGetById = '${AppConstants.apiBaseUrl}/api/v1/puzzles/{id}';
  static final String puzzlesCreate = '${AppConstants.apiBaseUrl}/api/v1/puzzles';
  static final String puzzlesAddImage = '${AppConstants.apiBaseUrl}/api/v1/puzzles/{puzzleId}/images';
  static final String puzzlesLogPuzzle = '${AppConstants.apiBaseUrl}/api/v1/puzzles/{puzzleId}/log';
  static final String puzzlesDefault = '${AppConstants.apiBaseUrl}/api/v1/puzzles/default';
  static final String puzzlesDefaults = '${AppConstants.apiBaseUrl}/api/v1/puzzles/defaults';
  static final String puzzlesByUser = '${AppConstants.apiBaseUrl}/api/v1/puzzles/user';
  static final String imagesGetAll = '${AppConstants.apiBaseUrl}/api/v1/images';
  static final String imagesGetById = '${AppConstants.apiBaseUrl}/api/v1/images/{id}';
  static final String imagesUpload = '${AppConstants.apiBaseUrl}/api/v1/images/upload';
  static final String imagesDelete = '${AppConstants.apiBaseUrl}/api/v1/images/{id}';
  static final String imagesUpdate = '${AppConstants.apiBaseUrl}/api/v1/images/{id}';
  static final String imagesAzureBlobs = '${AppConstants.apiBaseUrl}/api/v1/images/azureblobs';
  static final String imagesTestGroup = '${AppConstants.apiBaseUrl}/api/v1/images/group/test';
  static final String imagesFilegroups = '${AppConstants.apiBaseUrl}/api/v1/images/filegroups';
  static final String imagesFilegroup = '${AppConstants.apiBaseUrl}/api/v1/images/filegroup/{groupName}';
  static final String usersGetAll = '${AppConstants.apiBaseUrl}/api/v1/users';
  static final String usersGetById = '${AppConstants.apiBaseUrl}/api/v1/users/{id}';
  static final String usersCreate = '${AppConstants.apiBaseUrl}/api/v1/users';
  static final String usersLogin = '${AppConstants.apiBaseUrl}/api/v1/users/login';
  static final String usersUpdate = '${AppConstants.apiBaseUrl}/api/v1/users/{id}';
  static final String usersDelete = '${AppConstants.apiBaseUrl}/api/v1/users/{id}';
  static final String samplesGet = '${AppConstants.apiBaseUrl}/api/v1/samples';
  static final String samplesGetAdmin = '${AppConstants.apiBaseUrl}/api/v1/samples/user/admin';
  static final String samplesGetWriter = '${AppConstants.apiBaseUrl}/api/v1/samples/user/writer';
  static final String samplesGetReader = '${AppConstants.apiBaseUrl}/api/v1/samples/user/reader';
  static final String samplesGetRoleReader = '${AppConstants.apiBaseUrl}/api/v1/samples/role/reader';
  static final String samplesGetRoleWriter = '${AppConstants.apiBaseUrl}/api/v1/samples/role/writer';
}
