// This file is auto-generated from the API routes in MemoryPuzzleApi.
// Do not edit this file directly, changes will be overwritten.
import '../utils/constants.dart';
class ApiEndpoints {
  static const String apiBaseUrl = AppConstants.apiBaseUrl;
  static final String puzzlesGetAll = '${AppConstants.apiBaseUrl}/api/v1/puzzles';
  static final String puzzlesGetById = '${AppConstants.apiBaseUrl}/api/v1/puzzles/{id}';
  static final String puzzlesCreate = '${AppConstants.apiBaseUrl}/api/v1/puzzles';
  static final String puzzlesAddImage = '${AppConstants.apiBaseUrl}/api/v1/puzzles/{puzzleId}/images';
  static final String puzzlesLogPuzzle = '${AppConstants.apiBaseUrl}/api/v1/puzzles/{puzzleId}/log';
  static final String puzzlesDefault = '${AppConstants.apiBaseUrl}/api/v1/puzzles/default';
  static final String puzzlesDefaults = '${AppConstants.apiBaseUrl}/api/v1/puzzles/defaults';
  static final String imagesGetAll = '${AppConstants.apiBaseUrl}/api/v1/images';
  static final String imagesGetById = '${AppConstants.apiBaseUrl}/api/v1/images/{id}';
  static final String imagesUpload = '${AppConstants.apiBaseUrl}/api/v1/images/upload';
  static final String imagesDelete = '${AppConstants.apiBaseUrl}/api/v1/images/{id}';
  static final String imagesUpdate = '${AppConstants.apiBaseUrl}/api/v1/images/{id}';
  static final String imagesGetByPuzzleId = '${AppConstants.apiBaseUrl}/api/v1/images/puzzle/{puzzleId}';
  static final String imagesAzureBlobs = '${AppConstants.apiBaseUrl}/api/v1/images/azureblobs';
  static final String imagesTestGroup = '${AppConstants.apiBaseUrl}/api/v1/images/group/test';
  static final String usersGetAll = '${AppConstants.apiBaseUrl}/api/v1/users';
  static final String usersGetById = '${AppConstants.apiBaseUrl}/api/v1/users/{id}';
  static final String usersCreate = '${AppConstants.apiBaseUrl}/api/v1/users';
  static final String usersLogin = '${AppConstants.apiBaseUrl}/api/v1/users/login';
  static final String usersUpdate = '${AppConstants.apiBaseUrl}/api/v1/users/{id}';
  static final String usersDelete = '${AppConstants.apiBaseUrl}/api/v1/users/{id}';
  static final String samplesGet = '${AppConstants.apiBaseUrl}/api/v1/samples';
  static final String samplesGetAdmin = '${AppConstants.apiBaseUrl}/api/v1/samples/user/admin';
  static final String samplesGetWriter = '${AppConstants.apiBaseUrl}/api/v1/samples/user/writer';
  static final String samplesGetReader = '${AppConstants.apiBaseUrl}/api/v1/samples/user/reader';
  static final String samplesGetRoleReader = '${AppConstants.apiBaseUrl}/api/v1/samples/role/reader';
  static final String samplesGetRoleWriter = '${AppConstants.apiBaseUrl}/api/v1/samples/role/writer';
  static final String samplesCreateAdmin = '${AppConstants.apiBaseUrl}/api/v1/samples/admin';
  static final String samplesCreateUsers = '${AppConstants.apiBaseUrl}/api/v1/samples/users';
  static final String samplesDeleteUsers = '${AppConstants.apiBaseUrl}/api/v1/samples/users';
  static final String samplesDartExporter = '${AppConstants.apiBaseUrl}/api/v1/samples/exportroutes';
}
